[package]
name = "airbender"
version = "0.1.0"
authors = ["Jill Please <jillplspls@example.com>"]
edition = "2018"

[dependencies]
amethyst="0.15.3"

[features]
default = ["vulkan"]
vulkan = ["amethyst/vulkan"]
